// Code generated by goctl. DO NOT EDIT.
package types

type BucketResp struct {
	Name         string `json:"name"`
	CreationDate string `json:"creationDate"`
}

type FileGetRequest struct {
	Bucket string `path:"bucket"`
	Name   string `json:"name"`
	Path   string `json:"path"`
}

type FileUploadRequest struct {
	Bucket string `path:"bucket"`
}

type FileUploadResponse struct {
	Identity string `json:"identity"`
	Msg      string `json:"msg"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}

type ListBucketResp struct {
	List []BucketResp `json:"list"`
}

type ListObjResp struct {
	List []BucketResp `json:"list"`
}

type ObjReq struct {
	Bucket string `path:"bucket"`
}
