// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"minio/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bucket/list",
				Handler: ListBucketHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bucket/objs/:bucket",
				Handler: ListObjHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/get/:bucket",
				Handler: FileGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/upload/:bucket",
				Handler: FileUploadHandler(serverCtx),
			},
		},
	)
}
